#!/bin/bash
# Build asm/tk/main.asm into a loadable TestKernel.cubin via RCAsm injection.
#
#   RCASM=/path/to/RCAsm ./build.sh
#
# Inputs are main.asm (the kernel) and inc.asm (the field routines it calls). Output is
# TestKernel.cubin, which rcasm_test/abtest loads as the B side against GpuCore.cu.
#
# Needs, and none of it is optional:
#   RCASM     a checkout containing cuAssembler/.  Fixes 1-4 of asm/TESTKERNEL_TEMPLATE.md
#             §6 are applied IN-PROCESS by rc_build.py and by step 2/3 below, so the tree
#             itself does not have to be edited. It does need a taught sm_120 encoder
#             repository at cuAssembler/CuAsm/InsAsmRepos/DefaultInsAsmRepos.sm_120.txt.
#   PYDEPS    directory holding pyelftools and sympy, if python3 cannot already import them.
#   CUDA      toolkit root, default /usr/local/cuda. Needs nvcc, nvdisasm and cuobjdump.
#
# Verified working 2026-08-18 on CUDA 13.0.88 with python3 3.10.
set -e
cd "$(dirname "$0")"
if [ -z "$RCASM" ]; then
    echo "RCASM is not set. Point it at the RCAsm checkout (the directory containing" >&2
    echo "cuAssembler/). Add PYDEPS=<dir with pyelftools+sympy> if python3 lacks them." >&2
    echo "The built cubins are committed, so you only need this if an .asm changed." >&2
    exit 1
fi
CUDA="${CUDA:-/usr/local/cuda}"
WORK="${WORK:-/tmp/tkbuild}"
ASM="$(cd .. && pwd)"          # repo asm/ -- holds tmpl_TestKernel.cu
OUT="$(pwd)"

rm -rf "$WORK" && mkdir -p "$WORK"

# The project directory is assembled rather than committed: RCAsm concatenates EVERY .asm
# in PROJECT_PATH, so it must contain main.asm and the arithmetic units and NOTHING else --
# asm/ also holds Kernel02's own main.asm/fuse.asm/newKernelB.asm, which declare their own
# KERNELs and would collide.
#
# This used to copy mod_mul.asm, mod_sub.asm and mod_inv.asm straight out of asm/. It now
# takes asm/tk/inc.asm, which carries exactly the fourteen FUNCTIONs main.asm reaches --
# line-for-line the same bodies, generated by extraction rather than transcribed, and four
# unused routines lighter. Two things follow: the build no longer depends on a tree this
# kernel does not otherwise use, and a change to the arithmetic (C8's conditional subtract
# is the one on the list) has a local file to land in.
# MAIN selects the kernel source (variants.py generates a bisect ladder), INC the arithmetic
# it calls, OUTNAME the resulting cubin. Defaults reproduce the committed TestKernel.cubin.
# INC exists because a variant that perturbs the FUNCTION bodies -- a stall calibration, and
# C8's conditional subtract when it lands -- cannot use the committed inc.asm.
MAIN="${MAIN:-$OUT/main.asm}"
INC="${INC:-$OUT/inc.asm}"
OUTNAME="${OUTNAME:-TestKernel.cubin}"
cp "$INC" "$WORK"/inc.asm
cp "$MAIN" "$WORK"/main.asm
echo "project: $(cd "$WORK" && ls *.asm | tr '\n' ' ')   (kernel from $MAIN)"

# 1. Template -> cubin. Two-step device link, not `-rdc=true -cubin`: the single-step
#    form emits ELF type REL with undefined symbols and cuModuleLoad takes only EXEC.
#    -rdc is what gives the five __constant__ tables GLOBAL binding so the host can
#    find them with cuModuleGetGlobal; extern "C" alone does not (measured).
F="-O3 -std=c++17 -gencode arch=compute_120,code=sm_120"
"$CUDA/bin/nvcc" $F -rdc=true -c   -o "$WORK/tmpl.o" "$ASM/tmpl_TestKernel.cu"
"$CUDA/bin/nvcc" $F -rdc=true -dlink -cubin -o "$WORK/kernel_sm120.cubin" "$WORK/tmpl.o"
cp -f "$WORK/kernel_sm120.cubin" "$WORK/kernel_sm120.cubin_orig"

echo "--- template ---"
readelf -h "$WORK/kernel_sm120.cubin" 2>/dev/null | grep -E "Type:|Flags:"
"$CUDA/bin/cuobjdump" -res-usage "$WORK/kernel_sm120.cubin" | grep -E "REG:|STACK:"

# 2. cubin -> cuasm, in-process.
#
#    NOT `bin/cuasm.py`: that is a separate process, so it picks up config.py's
#    hardcoded NVDISASM_PATH = /usr/local/cuda-12.8/bin/nvdisasm ("ONLY 12.8 IS
#    TESTED!") and dies with FileNotFoundError before doing anything. Setting Config
#    here instead means this build does not require fix 1 to have been applied to the
#    RCAsm tree -- one less unversioned precondition. Step 4 runs in-process too and
#    sets the same thing.
export PYTHONPATH="$RCASM/cuAssembler${PYDEPS:+:$PYDEPS}"
NVDISASM="${NVDISASM:-$CUDA/bin/nvdisasm}" python3 - "$WORK/kernel_sm120.cubin" "$WORK/kernel_sm120.cuasm" <<'PY'
import os, sys
from CuAsm import CubinFile
from CuAsm.config import Config
Config.NVDISASM_PATH = os.environ["NVDISASM"]
Config.SM_VER = 120
CubinFile(sys.argv[1]).saveAsCuAsm(sys.argv[2])
print("disassembled -> %s" % sys.argv[2])
PY

# 3. Neutralize the bare .tkinfo directive. CUDA 13's nvdisasm emits a directive
#    CuAsmParser has no handler for; the string appears nowhere in cuAssembler. Only
#    the single bare line -- the other matches are comments. Without this, parse()
#    asserts, cuasm2cubin swallows it into False, and create_cubin returns before
#    patch_cubin is ever reached (which is why the .cuver KeyError went unobserved).
python3 - "$WORK/kernel_sm120.cuasm" <<'PY'
import re, sys
p = sys.argv[1]
L = open(p).read().splitlines()
n = 0
for i, ln in enumerate(L):
    if re.match(r"^\s*\.tkinfo\s*$", ln):
        L[i] = "//" + ln; n += 1
open(p, "w").write("\n".join(L) + "\n")
print("neutralized .tkinfo x%d" % n)
PY

# 4. Compile main.asm and inject it, then reassemble and patch the note sections back.
python3 "$OUT/rc_build.py" "$RCASM" "$WORK" 120

# 5. Results.
cp -f "$WORK/kernel_sm120.cubin" "$OUT/$OUTNAME"
echo "--- injected ---"
readelf -h "$OUT/$OUTNAME" 2>/dev/null | grep -E "Type:|Flags:"
"$CUDA/bin/cuobjdump" -res-usage "$OUT/$OUTNAME"
echo "--- instruction count ---"
"$CUDA/bin/cuobjdump" -sass "$OUT/$OUTNAME" | grep -cP '^\s+/\*[0-9a-f]+\*/' || true

echo
echo "wrote $OUT/$OUTNAME"
echo "NOTE: use cuobjdump, not nvdisasm -- nvdisasm refuses any kernel containing BRXU,"
echo "      which is RCAsm's own call/loop idiom."
