// asm/tk/inc.asm -- the field-arithmetic units this kernel actually uses.
//
// GENERATED BY asm/tk/mkinc.py -- DO NOT HAND-EDIT WITHOUT READING THAT FILE FIRST.
// Every instruction line below is copied byte-for-byte out of Kernel02's asm/mod_mul.asm,
// asm/mod_sub.asm and asm/mod_inv.asm, and the generator diffs each body back against its
// origin line for line before writing. It is generated rather than transcribed on purpose:
// these are hand-scheduled control codes, one wrong character is a wrong answer on hardware
// and not a build failure, and asm/tk/README.md records three defects of exactly that shape.
//
// WHY THIS FILE EXISTS. build.sh used to copy mod_mul.asm, mod_sub.asm and mod_inv.asm into
// the project directory at build time, because RCAsm concatenates every .asm it finds there
// and asm/ also holds Kernel02's own main.asm/fuse.asm/newKernelB.asm, which declare their
// own KERNELs. That kept one copy of the sources but made the build depend on a tree this
// kernel does not otherwise use, and pulled in four routines it never calls.
//
// WHAT IS HERE AND WHAT IS NOT. Exactly the transitive closure of what main.asm calls:
//
//     Copy256                      every 256-bit copy in main.asm goes through this
//     SubMod256  SubMod256_3  NegMod256
//     MulMod256  SqrMod256
//     InvMod256  + its seven _-prefixed helpers, all of which it uses
//
// Deliberately absent, because nothing reaches them: MadMod256 and SqrAddMod256 (mod_mul),
// AddMod256 and Zero256 (mod_sub). Dropping them changes no emitted byte -- RCAsm only ever
// emits a body some inc_func/call_func names -- so this is a smaller file to audit and
// nothing else. Anything main.asm adds a call to must be added to mkinc.py's WANT list too.
//
// Copy256's tail is S05, and that is load-bearing rather than incidental: it is the longest
// tail of the eight hand-written copy blocks it replaced, so every substitution LENGTHENED a
// stall or left it alone. Shortening one is what reads a stale register. See README.md.
//
// THE PRECONDITIONS TRAVEL WITH THE CODE, and two of them are not in the headers below:
//
//   * InvMod256 REQUIRES ALL ACTIVE THREADS IN THE WARP (its own comment, kept below). The
//     batch loop's uniform trip count is what supplies that; see main.asm's note on rem.
//   * InvMod256's Ro is NINE registers and its Rt is SEVENTY-THREE -- neither is the number
//     its own header advertises (Rt_cnt = 70). Both were found by measuring the emitted
//     cubin. Getting Ro wrong lands its overflow word on Rt0 and corrupts every inversion,
//     in a build that assembles and passes every offline checker. See main.asm's register
//     table, which is where the allocation those numbers constrain actually lives.
//
// C8 APPLIES TO MulMod256 AND SqrMod256 AS WRITTEN. They return a*b mod P in [0, 2^256)
// rather than [0, P) -- no final conditional subtract -- exactly as GpuCore.cu's mul_mod
// does. Measured on hardware: (P-1)^2 and 2*(P+1)/2 both come back as P+1. That is fine for
// the points-only kernel, which consumes no parity, and it is NOT fine once the hash layer
// returns, because the compressed-pubkey prefix is derived from bit 0 and P is odd. Fixing
// it is a change to THIS file, and the first one that will make mkinc.py report a mismatch.

//---- Copy256  <- asm/mod_sub.asm --------------------------------------------------
FUNCTION Copy256()
{
    [B------:R-:W-:-:S01]    IMAD Ro0, RZ, RZ, Ri0
    [B------:R-:W-:-:S01]    MOV Ro1, Ri1
    [B------:R-:W-:-:S01]    IMAD Ro2, RZ, RZ, Ri2
    [B------:R-:W-:-:S01]    MOV Ro3, Ri3
    [B------:R-:W-:-:S01]    IMAD Ro4, RZ, RZ, Ri4
    [B------:R-:W-:-:S01]    MOV Ro5, Ri5
    [B------:R-:W-:-:S01]    IMAD Ro6, RZ, RZ, Ri6
    [B------:R-:W-:-:S05]    MOV Ro7, Ri7
}

//---- SubMod256  <- asm/mod_sub.asm ------------------------------------------------
FUNCTION SubMod256()
{ //Ri_cnt=8+8, Ro_cnt=8, Pt=[0..1]
    [B------:R-:W-:-:S04]    IADD3.X Ro0, Pt0, PT, RFirst0, ~RSecond0, RZ, !PT, PT
    [B------:R-:W-:-:S04]    IADD3.X Ro1, Pt0, PT, RFirst1, ~RSecond1, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro2, Pt0, PT, RFirst2, ~RSecond2, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro3, Pt0, PT, RFirst3, ~RSecond3, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro4, Pt0, PT, RFirst4, ~RSecond4, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro5, Pt0, PT, RFirst5, ~RSecond5, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro6, Pt0, PT, RFirst6, ~RSecond6, RZ, Pt0, !PT
    [B------:R-:W-:Y:S13]    IADD3.X Ro7, Pt0, PT, RFirst7, ~RSecond7, RZ, Pt0, !PT
//add P if <0
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro0, Pt1, PT, Ro0, 0xFFFFFC2F, RZ, !PT, !PT
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro1, Pt1, PT, Ro1, 0xFFFFFFFE, RZ, Pt1, !PT
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro2, Pt1, PT, Ro2, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro3, Pt1, PT, Ro3, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro4, Pt1, PT, Ro4, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro5, Pt1, PT, Ro5, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S04] @!Pt0 IADD3.X Ro6, Pt1, PT, Ro6, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S05] @!Pt0 IADD3.X Ro7, PT, PT, Ro7, 0xFFFFFFFF, RZ, Pt1, !PT
}

//---- SubMod256_3  <- asm/mod_sub.asm ----------------------------------------------
FUNCTION SubMod256_3()
{ //Ri_cnt=8+8+8, Ro_cnt=8, Rt_cnt=2, Pt=[0..2]
//reg bank conflict is possible
//
// STALLS WIDENED FROM THE VENDORED VALUES, 2026-08-15. The originals are kept in the
// trailing comment on each changed line.
//
// Kernel02's sources have only ever been through RCAsm's front end -- they have never been
// assembled or executed -- so their stall counts are unverified rather than blessed, and
// this routine is the first thing stage 2c-ii runs that had never run anywhere.
//
// Two dependencies here were the tightest in the routine, and the tail point came back
// wrong by exactly 2^224 + 0x7A1, which decomposes cleanly across the two:
//
//   Ro6 wrote Pt0/Pt2 at S01, and Ro7 read them across only the MOV -- TWO cycles.
//   Simulating Ro7 with the stale pair reproduces +2^224 exactly, the word-7 half.
//
//   SEL wrote Rt0 at S04 and the first correction read it one instruction later. Forcing
//   that word-0 constant to 0xFFFFFFFF instead of 2P's 0xFFFFF85E reproduces +0x7A1
//   exactly, the word-0 half -- and 0xFFFFF85E + 0x7A1 == 0xFFFFFFFF is not a coincidence.
//
// Everything cheaper was eliminated first: the routine is congruent-correct over 20,000
// random triples in simulation, the body emitted into the cubin is byte-for-byte what is
// written here, its three inputs are confirmed on hardware (lam and lam^2 both report ok),
// and no other emitted body writes Ro's registers after this one produces them. The
// arithmetic had nowhere left to be wrong.
//
// CONFIRMED ON HARDWARE, same day: with only this changed, stage 2c-ii's pts rung came back
// EXACT on all 256 threads and the tail chain reports lam ok / lam^2 ok / px3 ok. The
// prediction was falsifiable -- a still-wrong px3 would have killed the timing story and made
// both reproductions above coincidence -- and it held.
//
// WHAT IS CONFIRMED IS THE FIX, NOT THE MECHANISM, and the obvious reading of it is wrong.
// "Two cycles is below the floor for a carry-in predicate" does not survive the cubin:
// MulMod256, SqrMod256 and InvMod256 contain 126 carry-out -> carry-in pairs at two cycles
// between them, and all three are correct on hardware. What separates this routine from those
// 126 is not the distance, it is what sits in the gap -- every one of them spans an IADD3,
// IMAD or SHF, and this was the only two-cycle pair in the kernel spanning a MOV. That is one
// instance, and the widening below changed fifteen lines rather than the one, so it is a
// candidate and not a finding.
//
// NARROWING IT IS ONE RUN, and a sharp one: restore the originals except instruction 7's
// stall. The delta has two halves and they are attributed separately, so if the 2^224 half
// disappears and the 0x7A1 half does not, the run has separated the two claims above by
// itself. Worth doing when a hardware run is being spent anyway; not worth one of its own,
// since this is 18 instructions against 1023 calls per thread.
    [B------:R-:W-:-:S06]    IADD3.X Ro0, Pt0, Pt2, RFirst0, ~RSecond0, ~RThird0, PT, PT
    [B------:R-:W-:-:S06]    IADD3.X Ro1, Pt0, Pt2, RFirst1, ~RSecond1, ~RThird1, Pt0, Pt2
    [B------:R-:W-:-:S06]    IADD3.X Ro2, Pt0, Pt2, RFirst2, ~RSecond2, ~RThird2, Pt0, Pt2
    [B------:R-:W-:-:S06]    IADD3.X Ro3, Pt0, Pt2, RFirst3, ~RSecond3, ~RThird3, Pt0, Pt2
    [B------:R-:W-:-:S06]    IADD3.X Ro4, Pt0, Pt2, RFirst4, ~RSecond4, ~RThird4, Pt0, Pt2
    [B------:R-:W-:-:S06]    IADD3.X Ro5, Pt0, Pt2, RFirst5, ~RSecond5, ~RThird5, Pt0, Pt2
    [B------:R-:W-:-:S06]    IADD3.X Ro6, Pt0, Pt2, RFirst6, ~RSecond6, ~RThird6, Pt0, Pt2  //was S01
    [B------:R-:W-:-:S06]    MOV Rt1, 0xFFFFFC2F                                            //was S01
    [B------:R-:W-:Y:S09]    IADD3.X Ro7, Pt0, Pt2, RFirst7, ~RSecond7, ~RThird7, Pt0, Pt2
    [B------:R-:W-:-:S06]    SEL Rt0, Rt1, 0xFFFFF85E, Pt0                                  //was S04
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro0, Pt1, PT, Ro0, Rt0, RZ, !PT, !PT
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro1, Pt1, PT, Ro1, 0xFFFFFFFD, RZ, Pt1, Pt0
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro2, Pt1, PT, Ro2, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro3, Pt1, PT, Ro3, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro4, Pt1, PT, Ro4, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro5, Pt1, PT, Ro5, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro6, Pt1, PT, Ro6, 0xFFFFFFFF, RZ, Pt1, !PT
    [B------:R-:W-:-:S06] @!Pt2 IADD3.X Ro7, PT,  PT, Ro7, 0xFFFFFFFF, RZ, Pt1, !PT         //was S05
}

//---- NegMod256  <- asm/mod_sub.asm ------------------------------------------------
FUNCTION NegMod256()
{
    [B------:R-:W-:-:S04]    IADD3.X Rio0, Pt0, PT, RZ, 0xFFFFFC2F, ~Rio0, !PT, PT
    [B------:R-:W-:-:S04]    IADD3.X Rio1, Pt0, PT, RZ, 0xFFFFFFFE, ~Rio1, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Rio2, Pt0, PT, RZ, 0xFFFFFFFF, ~Rio2, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Rio3, Pt0, PT, RZ, 0xFFFFFFFF, ~Rio3, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Rio4, Pt0, PT, RZ, 0xFFFFFFFF, ~Rio4, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Rio5, Pt0, PT, RZ, 0xFFFFFFFF, ~Rio5, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Rio6, Pt0, PT, RZ, 0xFFFFFFFF, ~Rio6, Pt0, !PT
    [B------:R-:W-:-:S05]    IADD3.X Rio7, PT, PT, RZ, 0xFFFFFFFF, ~Rio7, Pt0, !PT
}

//---- MulMod256  <- asm/mod_mul.asm ------------------------------------------------
FUNCTION MulMod256()
{ //Ri_cnt=8+8, Ro_cnt=8, Rt_cnt=20, P=[0..4]
////start MulMod256
//0: 0A 0C
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Ro0, RFirst0.reuse, RSecond0, RZ
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Ro2, RFirst0, RSecond2, RZ
//2: 1B 0E
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro2, Pt4, RFirst1.reuse, RSecond1, Ro2
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Ro4, RFirst0, RSecond4, RZ, Pt4
//2: 2A 1D 0G
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro2, Pt4, RFirst2, RSecond0, Ro2
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Ro4, Pt4, RFirst1.reuse, RSecond3, Ro4, Pt4
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Ro6, RFirst0, RSecond6, RZ, Pt4
//4: 2C 1F 1H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro4, Pt4, RFirst2, RSecond2, Ro4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Ro6, Pt4, RFirst1.reuse, RSecond5, Ro6, Pt4
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt12, RFirst1, RSecond7, RZ, Pt4
//4: 3B 2E 2G 3H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro4, Pt4, RFirst3, RSecond1, Ro4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Ro6, Pt4, RFirst2.reuse, RSecond4, Ro6, Pt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt12, Pt4, RFirst2, RSecond6, Rt12, Pt4
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt14, PT, RFirst3.reuse, RSecond7, RZ, Pt4
//4: 4A 3D 3F 4G 5H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro4, Pt4, RFirst4, RSecond0, Ro4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Ro6, Pt4, RFirst3.reuse, RSecond3, Ro6, Pt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt12, Pt4, RFirst3, RSecond5, Rt12, Pt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt14, Pt4, RFirst4.reuse, RSecond6, Rt14, Pt4
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt16, RFirst5, RSecond7, RZ, Pt4
//6: 4C 4E 5F 6G 7H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro6, Pt4, RFirst4.reuse, RSecond2, Ro6
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt12, Pt4, RFirst4, RSecond4, Rt12, Pt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt14, Pt4, RFirst5, RSecond5, Rt14, Pt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt16, Pt4, RFirst6, RSecond6, Rt16, Pt4
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt18, RFirst7, RSecond7, RZ, Pt4
//6: 5B 5D 6E 7F, get C3
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro6, Pt4, RFirst5.reuse, RSecond1, Ro6
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt12, Pt4, RFirst5, RSecond3, Rt12, Pt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt14, Pt4, RFirst6.reuse, RSecond4, Rt14, Pt4
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt16, Pt3, RFirst7, RSecond5, Rt16, Pt4
//6: 6A 6C 7D, get C2
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Ro6, Pt4, RFirst6.reuse, RSecond0, Ro6
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt12, Pt4, RFirst6, RSecond2, Rt12, Pt4
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt14, Pt2, RFirst7.reuse, RSecond3, Rt14, Pt4
//8: 7B, get C1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt12, Pt1, RFirst7, RSecond1, Rt12
///////////////////////////////
//0: 0B
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt0, RFirst0, RSecond1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt10, RZ, RZ, RZ, Pt1, !PT //C1 to Rt10
//0: 1A 0D
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Rt0, Pt0, RFirst1, RSecond0, Rt0
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt2, RFirst0, RSecond3, RZ, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Rt11, RZ, RZ, RZ, Pt2, !PT //C2 to Rt11
//2: 1C 0F
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt2, Pt0, RFirst1, RSecond2, Rt2
    [B------:R-:W-:-:S01]    IADD3.X Rt18, Pt1, PT, Rt18, RZ, RZ, Pt3, !PT //now use C3 and C7 and forget
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt4, RFirst0, RSecond5, RZ, Pt0
    [B------:R-:W-:-:S01]    IADD3 Ro1, Pt3, Ro1, Rt0, RZ //build res
//2: 2B 1E 0H
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt2, Pt0, RFirst2, RSecond1, Rt2
    [B------:R-:W-:-:S01]    IADD3.X Ro2, Pt3, Ro2, Rt1, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt4, Pt0, RFirst1, RSecond4, Rt4, Pt0
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt0, RFirst0, RSecond7, RZ, Pt0
//2: 3A 2D 1G 2H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Rt2, Pt0, RFirst3, RSecond0, Rt2
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt4, Pt0, RFirst2, RSecond3, Rt4, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro3, Pt3, Ro3, Rt2, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32.X Rt0, Pt0, RFirst1, RSecond6, Rt0, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt3, Ro4, Rt3, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt2, RFirst2, RSecond7, RZ, Pt0
//4: 3C 2F 3G 4H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Rt4, Pt0, RFirst3, RSecond2, Rt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt0, Pt0, RFirst2, RSecond5, Rt0, Pt0
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt2, Pt0, RFirst3, RSecond6, Rt2, Pt0
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt6, RFirst4, RSecond7, RZ, Pt0
//4: 4B 3E 4F 5G 6H
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Rt4, Pt0, RFirst4, RSecond1, Rt4
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt0, Pt0, RFirst3, RSecond4, Rt0, Pt0
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt2, Pt0, RFirst4, RSecond5, Rt2, Pt0
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt6, Pt0, RFirst5, RSecond6, Rt6, Pt0
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt8, RFirst6, RSecond7, RZ, Pt0
//4: 5A 4D 5E 6F 7G, get C7(store in Pt4)
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Rt4, Pt0, RFirst5, RSecond0, Rt4
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt0, Pt0, RFirst4, RSecond3, Rt0, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro5, Pt3, Ro5, Rt4, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt2, Pt0, RFirst5, RSecond4, Rt2, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro6, Pt3, Ro6, Rt5, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt6, Pt0, RFirst6, RSecond5, Rt6, Pt0
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt8, Pt4, RFirst7, RSecond6, Rt8, Pt0
//6: 5C 6D 7E, get C6
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt0, Pt0, RFirst5, RSecond2, Rt0
    [B------:R-:W-:-:S01]    IADD3.X Rt19, PT, PT, Rt19, RZ, RZ, Pt1, Pt4 //now use C3 and C7 and forget
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32.X Rt2, Pt0, RFirst6, RSecond3, Rt2, Pt0
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt6, Pt1, RFirst7, RSecond4, Rt6, Pt0 //C6 to Pt1
//6: 6B 7C, get C5
    [B------:R-:W-:-:S04]    IMAD.WIDE.U32 Rt0, Pt0, RFirst6, RSecond1, Rt0

    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt2, Pt2, RFirst7, RSecond2, Rt2, Pt0
//6: 7A, get C4
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt0, Pt4, RFirst7, RSecond0, Rt0
    [B------:R-:W-:-:S01]    IADD3.X Rt4, RZ, RZ, RZ, Pt2, !PT //C5 to Rt4
    [B------:R-:W-:-:S04]    IADD3.X Ro7, Pt3, Ro7, Rt0, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S04]    IADD3.X Rt12, Pt3, Rt12, Rt1, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S01]    IADD3.X Rt13, Pt3, Pt4, Rt13, Rt2, RZ, Pt3, Pt4 //build res
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt0, Rt12, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt14, Pt3, Pt4, Rt14, Rt3, Rt10, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IADD3.X Rt10, RZ, RZ, RZ, Pt1, !PT //C6 to Rt10
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt2, Pt2, Rt13, 0x3D1, Rt12, !PT
    [B------:R-:W-:-:S01]    IADD3.X Rt15, Pt3, Pt4, Rt15, Rt6, Rt4, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IADD3.X Ro0, Pt0, Pt1, Ro0, Rt0, RZ, !PT, !PT
    [B------:R-:W-:-:S01]    IADD3.X Rt16, Pt3, Pt4, Rt16, Rt7, Rt11, Pt3, Pt4 //build res
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt4, Rt14, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt17, Pt3, Pt4, Rt17, Rt8, Rt10, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IADD3.X Ro1, Pt0, Pt1, Rt1, Rt2, Ro1, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Rt18, Pt3, Pt4, Rt18, Rt9, RZ, Pt3, Pt4 //build res
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt6, Pt2, Rt15, 0x3D1, Rt14, Pt2
    [B------:R-:W-:-:S01]    IADD3.X Rt19, Rt19, RZ, RZ, Pt3, Pt4 //build res
// reduction
    [B------:R-:W-:-:S01]    IADD3.X Ro2, Pt0, Pt1, Rt3, Rt4, Ro2, Pt0, Pt1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt8, Rt16, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro3, Pt0, Pt1, Rt5, Rt6, Ro3, Pt0, Pt1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt4, Pt2, Rt17, 0x3D1, Rt16, Pt2
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt0, Rt18, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt0, Pt1, Rt7, Rt8, Ro4, Pt0, Pt1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt2, Pt2, Rt19, 0x3D1, Rt18, Pt2
    [B------:R-:W-:-:S04]    IADD3.X Ro5, Pt0, Pt1, Rt9, Rt4, Ro5, Pt0, Pt1
    [B------:R-:W-:-:S04]    IADD3.X Ro6, Pt0, Pt1, Rt5, Rt0, Ro6, Pt0, Pt1
    [B------:R-:W-:-:S04]    IADD3.X Ro7, Pt0, Pt1, Rt1, Rt2, Ro7, Pt0, Pt1
//Rt8..Rt9 is "tmp[4] in cpu code, Rt8 <= 0x3d1 (checked P-1*P-1), Rt9 <= 1
    [B------:R-:W-:-:S04]    IADD3.X Rt8, Pt0, PT, Rt3, RZ, RZ, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Rt9, Pt0, Pt1, RZ, RZ, RZ, Pt0, Pt2
////
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Ro0, Pt3, Rt8, 0x3D1, Ro0, !PT
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt2, Rt9, 0x3D1, Rt8 //no carry occurs!
    [B------:R-:W-:-:S04]    IADD3.X Ro1, Pt0, PT, Ro1, Rt2, RZ, !PT, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro2, Pt0, Pt1, Rt3, Ro2, RZ, Pt0, Pt3
    [B------:R-:W-:-:S04]    IADD3.X Ro3, Pt0, PT, Ro3, RZ, RZ, Pt0, Pt1
    [B------:R-:W-:-:S04]    IADD3.X Ro4, Pt0, PT, Ro4, RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro5, Pt0, PT, Ro5, RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro6, Pt0, PT, Ro6, RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S04]    IADD3.X Ro7, PT, PT, Ro7, RZ, RZ, Pt0, !PT
//now if P(carry) is 1 then we need Sub(256k1_P), chance is about 1/2^129 so just ignore it
////end MulMod256
}

//---- SqrMod256  <- asm/mod_mul.asm ------------------------------------------------
FUNCTION SqrMod256(First=Ri0)
{ //Ri_cnt=8, Ro_cnt=8, Ro_tmp=26, P=[0..5]
////start SqrMod256
//2: 0A 0C 1B
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt0, First0, First2, RZ
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Ro2, First1, First1, RZ
//4: OE 1D 2C
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt2, First0, First4, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro2, Pt0, Pt1, Ro2, Rt0, Rt0, !PT, !PT

    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Ro4, First2, First2, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro3, Pt0, Pt1, Ro3, Rt1, Rt1, Pt0, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt4, First1, First3, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt0, Pt1, Ro4, Rt2, Rt2, Pt0, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Ro0, First0, First0, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt2, Pt3, Ro4, Rt4, Rt4, !PT, !PT
//6: 0G 1F 2E 3D
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt6, First0, First6, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro5, Pt0, Pt1, Ro5, Rt3, Rt3, Pt0, Pt1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Ro6, First3, First3, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro5, Pt2, Pt3, Ro5, Rt5, Rt5, Pt2, Pt3
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt8,  First1, First5, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro6, Pt0, Pt1, Ro6, Rt6, Rt6, Pt0, Pt1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt10,  First2, First4, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro6, Pt2, Pt3, Ro6, Rt8, Rt8, Pt2, Pt3
//8: 1H 2G 3F 4E
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt12, First1, First7, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro6, Pt4, Pt5, Ro6, Rt10, Rt10, !PT, !PT
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt14, First2, First6, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro7, Pt0, Pt1, Ro7, Rt7, Rt7, Pt0, Pt1
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt0, First3, First5, RZ
    [B------:R-:W-:-:S02]    IADD3.X Ro7, Pt2, Pt3, Ro7, Rt9, Rt9, Pt2, Pt3
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32 Rt18, First4, First4, RZ
    [B------:R-:W-:-:S03]    IADD3.X Ro7, Pt4, Pt5, Ro7, Rt11, Rt11, Pt4, Pt5
//10: 3H 4G 5F
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt10, First3, First7, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt18, Pt0, Pt1, Rt18, Rt12, Rt12, Pt0, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt6, First4, First6, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt18, Pt2, Pt3, Rt18, Rt14, Rt14, Pt2, Pt3
//12: 5H 6H 7H
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt8, First5, First7, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt18, Pt4, Pt5, Rt18, Rt0, Rt0, Pt4, Pt5
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt24, First7, First7, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt19, Pt4, Pt5, Rt19, Rt1, Rt1, Pt4, Pt5  //Pt5 = C1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt0, First0, First1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt19, Pt0, Pt1, Rt19, Rt13, Rt13, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Rt14, RZ, RZ, RZ, Pt5, !PT //C1 to Rt14
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt20, PT, First5, First5, RZ, Pt4 //take one carry to imad
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt0, Pt5, First1, First0, Rt0
    [B------:R-:W-:-:S01]    IADD3.X Rt19, Pt2, Pt3, Rt19, Rt15, Rt15, Pt2, Pt3
    [B------:R-:W-:-:S01]    IADD3.X Rt20, Pt4, Pt1, Rt20, Rt10, Rt10, Pt0, Pt1
//10: add
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt2, First0, First3, RZ, Pt5
    [B------:R-:W-:-:S01]    IADD3.X Rt20, Pt2, Pt3, Rt20, Rt6, Rt6, Pt2, Pt3
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt2, Pt5, First1, First2, Rt2
    [B------:R-:W-:-:S02]    IADD3.X Rt21, Pt4, Pt1, Rt21, Rt11, Rt11, Pt4, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt4, First0, First5, RZ, Pt5
    [B------:R-:W-:-:S01]    IADD3.X Rt21, Pt2, Pt3, Rt21, Rt7, Rt7, Pt2, Pt3 //Pt3 = C2
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt2, Pt0, First2, First1, Rt2
    [B------:R-:W-:-:S01]    IADD3.X Rt15, RZ, RZ, RZ, Pt3, !PT //C2 to Rt15
//12: add
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt22, PT, First6, First6, RZ, Pt2 //take one carry to imad
    [B------:R-:W-:-:S01]    IADD3 Ro1, Pt3, Ro1, Rt0, RZ //build res
    [B------:R-:W-:-:S01]    IADD3.X Rt22, Pt4, Pt1, Rt22, Rt8, Rt8, Pt4, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt4, Pt0, First1, First4, Rt4, Pt0
    [B------:R-:W-:-:S02]    IADD3.X Rt23, Pt4, Pt1, Rt23, Rt9, Rt9, Pt4, Pt1  //Pt1 = C3
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt6, First0, First7, RZ, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Rt24, Pt4, Pt1, Rt24, RZ, RZ, Pt4, Pt1 //process C3 and forget
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt2, Pt0, First3, First0, Rt2
//14:
    [B------:R-:W-:-:S01]    IADD3.X Rt25, PT, PT, Rt25, RZ, RZ, Pt4, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Ro2, Pt3, Ro2, Rt1, RZ, Pt3, !PT //build res
//2: 3A 2D 1G 2H
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt4, Pt0, First2, First3, Rt4, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro3, Pt3, Ro3, Rt2, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32.X Rt6, Pt0, First1, First6, Rt6, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt3, Ro4, Rt3, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt8, First2, First7, RZ, Pt0
//4: 3C 2F 3G 4H
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32 Rt4, Pt0, First3, First2, Rt4
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt6, Pt0, First2, First5, Rt6, Pt0
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt8, Pt0, First3, First6, Rt8, Pt0
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt10, First4, First7, RZ, Pt0
//4: 4B 3E 4F 5G 6H
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32 Rt4, Pt0, First4, First1, Rt4
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt6, Pt0, First3, First4, Rt6, Pt0
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt8, Pt0, First4, First5, Rt8, Pt0
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt10, Pt0, First5, First6, Rt10, Pt0
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt12, First6, First7, RZ, Pt0
//4: 5A 4D 5E 6F 7G, get C7(store in Pt4)
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32 Rt4, Pt0, First5, First0, Rt4
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt6, Pt0, First4, First3, Rt6, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro5, Pt3, Ro5, Rt4, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S02]    IMAD.WIDE.U32.X Rt8, Pt0, First5, First4, Rt8, Pt0
    [B------:R-:W-:-:S01]    IADD3.X Ro6, Pt3, Ro6, Rt5, RZ, Pt3, !PT //build res
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt10, Pt0, First6, First5, Rt10, Pt0
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt12, Pt4, First7, First6, Rt12, Pt0
//6: 5C 6D 7E, get C6
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt6, Pt0, First5, First2, Rt6
    [B------:R-:W-:-:S01]    IADD3.X Rt25, PT, PT, Rt25, RZ, RZ, !PT, Pt4 //process C7 and forget
    [B------:R-:W-:Y:S04]    IMAD.WIDE.U32.X Rt8, Pt0, First6, First3, Rt8, Pt0
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt10, Pt2, First7, First4, Rt10, Pt0 //C6 to Pt2
//6: 6B 7C, get C5
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt6, Pt0, First6, First1, Rt6
    [B------:R-:W-:-:S01]    IADD3.X Rt17, RZ, RZ, RZ, Pt2, !PT //C6 to Rt17
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt8, Pt2, First7, First2, Rt8, Pt0
//6: 7A, get C4
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt6, Pt4, First7, First0, Rt6
    [B------:R-:W-:-:S01]    IADD3.X Rt16, RZ, RZ, RZ, Pt2, !PT //C5 to Rt16
    [B------:R-:W-:Y:S04]    IADD3.X Ro7, Pt3, Ro7, Rt6, RZ, Pt3, !PT //build res
    [B------:R-:W-:Y:S04]    IADD3.X Rt18, Pt3, Rt18, Rt7, RZ, Pt3, !PT //build res
    [B------:R-:W-:-:S01]    IADD3.X Rt19, Pt3, Pt4, Rt19, Rt8, RZ, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt0, Rt18, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt20, Pt3, Pt4, Rt20, Rt9, Rt14, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt2, Pt2, Rt19, 0x3D1, Rt18, !PT
    [B------:R-:W-:-:S01]    IADD3.X Rt21, Pt3, Pt4, Rt21, Rt10, Rt16, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IADD3.X Ro0, Pt0, Pt1, Ro0, Rt0, RZ, !PT, !PT
    [B------:R-:W-:-:S01]    IADD3.X Rt22, Pt3, Pt4, Rt22, Rt11, Rt15, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt4, Rt20, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Rt23, Pt3, Pt4, Rt23, Rt12, Rt17, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IADD3.X Ro1, Pt0, Pt1, Rt1, Rt2, Ro1, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Rt24, Pt3, Pt4, Rt24, Rt13, RZ, Pt3, Pt4 //build res
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt6, Pt2, Rt21, 0x3D1, Rt20, Pt2
    [B------:R-:W-:-:S01]    IADD3.X Rt25, Rt25, RZ, RZ, Pt3, Pt4 //build res
///////////////////////////////////////////////// reduction
    [B------:R-:W-:-:S01]    IADD3.X Ro2, Pt0, Pt1, Rt3, Rt4, Ro2, Pt0, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt8, Rt22, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro3, Pt0, Pt1, Rt5, Rt6, Ro3, Pt0, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt10, Pt2, Rt23, 0x3D1, Rt22, Pt2
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32 Rt12, Rt24, 0x3D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt0, Pt1, Rt7, Rt8, Ro4, Pt0, Pt1
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Rt14, Pt2, Rt25, 0x3D1, Rt24, Pt2
    [B------:R-:W-:Y:S04]    IADD3.X Ro5, Pt0, Pt1, Rt9, Rt10, Ro5, Pt0, Pt1
    [B------:R-:W-:Y:S04]    IADD3.X Ro6, Pt0, Pt1, Rt11, Rt12, Ro6, Pt0, Pt1
    [B------:R-:W-:Y:S04]    IADD3.X Ro7, Pt0, Pt1, Rt13, Rt14, Ro7, Pt0, Pt1
//Rt8..Rt9 is "tmp[4] in cpu code, Rt8 <= 0x3d1 (checked P-1*P-1), Rt9 <= 1
    [B------:R-:W-:Y:S04]    IADD3.X Rt8, Pt0, PT, Rt15, RZ, RZ, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Rt9, Pt0, Pt1, RZ, RZ, RZ, Pt0, Pt2
/////////////////////////////
    [B------:R-:W-:-:S01]    IMAD.WIDE.U32.X Ro0, Pt3, Rt8, 0x3D1, Ro0, !PT
    [B------:R-:W-:-:S03]    IMAD.WIDE.U32 Rt2, Rt9, 0x3D1, Rt8 //no carry occurs!
    [B------:R-:W-:Y:S04]    IADD3.X Ro1, Pt0, PT, Ro1, Rt2, RZ, !PT, !PT
    [B------:R-:W-:Y:S04]    IADD3.X Ro2, Pt0, Pt1, Rt3, Ro2, RZ, Pt0, Pt3
    [B------:R-:W-:Y:S04]    IADD3.X Ro3, Pt0, PT, Ro3, RZ, RZ, Pt0, Pt1
    [B------:R-:W-:Y:S04]    IADD3.X Ro4, Pt0, PT, Ro4, RZ, RZ, Pt0, !PT
    [B------:R-:W-:Y:S04]    IADD3.X Ro5, Pt0, PT, Ro5, RZ, RZ, Pt0, !PT
    [B------:R-:W-:Y:S04]    IADD3.X Ro6, Pt0, PT, Ro6, RZ, RZ, Pt0, !PT
    [B------:R-:W-:Y:S04]    IADD3.X Ro7, PT, PT, Ro7, RZ, RZ, Pt0, !PT
//now if P(carry) is 1 then we need Sub(256k1_P), chance is about 1/2^129 so just ignore it

////end SqrMod256
}

//---- _fast_find_first_bit  <- asm/mod_inv.asm -------------------------------------
FUNCTION _fast_find_first_bit()
{ //Ro_cnt=1, Rt_cnt=2, Rval, Rone, Rbc
////start _fast_find_first_bit
    [B------:R-:W-:-:S04]    SHF.L.U32 Rt0, Rone, Rbc, RZ
    [B------:R-:W-:-:S04]    LOP3.LUT Rt0, Rt0, Rval, RZ, 0xfc, !PT
    [B------:R-:W-:-:S04]    IADD3 Rt1, -Rt0, RZ, RZ //z=Rt0
    [B------:R-:W-:-:S04]    LOP3.LUT Rt0, Rt0, Rt1, RZ, 0xc0, !PT //(z & -z)
    [B------:R-:W-:-:S04]    I2FP.F32.S32 Rt0, Rt0
    [B------:R-:W-:-:S04]    LEA.HI Ro0, Rt0, 0xffffff81, RZ, 9 //(int >> 23) - 127
////end _fast_find_first_bit
}

//---- _mul_256_by_i32  <- asm/mod_inv.asm ------------------------------------------
FUNCTION _mul_256_by_i32(val=Rt8)
{ //Ro_cnt=9, Rt_cnt=6, Pt=[0..2]  Rval, Ri
////start _mul_256_by_i32
    [B------:R-:W-:-:S04] @Pt3 IABS val, Ri
    [B------:R-:W-:-:S01]    ISETP.LT.AND Pt1, PT, Ri, RZ, Pt3
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro0, Rval, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt0, Rval1, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro2, Rval2, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3 Ro1, Pt2, Ro1, Rt0, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt2, Rval3, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro2, Pt2, Ro2, Rt1, RZ, Pt2, !PT
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro0, Pt0, PT, RZ, ~Ro0, RZ, PT, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro4, Rval4, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro3, Pt2, Ro3, Rt2, RZ, Pt2, !PT
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro1, Pt0, PT, RZ, ~Ro1, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt4, Rval5, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro4, Pt2, Ro4, Rt3, RZ, Pt2, !PT
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro2, Pt0, PT, RZ, ~Ro2, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro6, Rval6, val.reuse, RZ
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro3, Pt0, PT, RZ, ~Ro3, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro5, Pt2, Ro5, Rt4, RZ, Pt2, !PT
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro4, Pt0, PT, RZ, ~Ro4, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt0, Rval7, val, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro6, Pt2, Ro6, Rt5, RZ, Pt2, !PT
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro5, Pt0, PT, RZ, ~Ro5, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro7, Pt2, Ro7, Rt0, RZ, Pt2, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro6, Pt0, PT, RZ, ~Ro6, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.X.U32 Ro8, Rval8, val, Rt1, Pt2
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro7, Pt0, PT, RZ, ~Ro7, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt1 IADD3.X Ro8, PT, PT, RZ, ~Ro8, RZ, Pt0, !PT
////end _mul_256_by_i32
}

//---- _mul_256_by_u31  <- asm/mod_inv.asm ------------------------------------------
FUNCTION _mul_256_by_u31()
{ //Ro_cnt=9, Rt_cnt=6, Pt=[0]  Rval, Ri
////start _mul_256_by_u31
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro0, Rval, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt0, Rval1, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro2, Rval2, Ri, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3 Ro1, Pt0, Ro1, Rt0, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt2, Rval3, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro2, Pt0, Ro2, Rt1, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro4, Rval4, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro3, Pt0, Ro3, Rt2, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt4, Rval5, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro4, Pt0, Ro4, Rt3, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Ro6, Rval6, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro5, Pt0, Ro5, Rt4, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt0, Rval7, Ri.reuse, RZ
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro6, Pt0, Ro6, Rt5, RZ, Pt0, !PT
    [B------:R-:W-:Y:S05] @Pt3 IADD3.X Ro7, Pt0, Ro7, Rt0, RZ, Pt0, !PT
    [B------:R-:W-:Y:S01] @Pt3 IMAD.X.U32 Ro8, Rval8, Ri, Rt1, Pt0
////end _mul_256_by_u31
}

//---- _mul_256_by_u31_add_shift  <- asm/mod_inv.asm --------------------------------
FUNCTION _mul_256_by_u31_add_shift(tmp=Rt6)
{ //Ro_cnt=9, Rt_cnt=15, Pt=[0,1]  Rval, Ri, Radd
////start _mul_256_by_u31_add_shift
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 tmp0, Rval, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt0, Rval1, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3 tmp0, Pt0, PT, tmp0, RZ, Radd0, !PT, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 tmp2, Rval2, Ri, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3 tmp1, Pt0, Pt1, tmp1, Rt0, Radd1, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt2, Rval3, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp2, Pt0, Pt1, tmp2, Rt1, Radd2, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 tmp4, Rval4, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp3, Pt0, Pt1, tmp3, Rt2, Radd3, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt4, Rval5, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp4, Pt0, Pt1, tmp4, Rt3, Radd4, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 tmp6, Rval6, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp5, Pt0, Pt1, tmp5, Rt4, Radd5, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 IMAD.WIDE.U32 Rt0, Rval7, Ri.reuse, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp6, Pt0, Pt1, tmp6, Rt5, Radd6, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro0, tmp0, 30, tmp1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro1, tmp1, 30, tmp2
    [B------:R-:W-:-:S01] @Pt3 IMAD.U32 tmp8, Rval8, Ri, Rt1
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp7, Pt0, Pt1, tmp7, Rt0, Radd7, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro2, tmp2, 30, tmp3
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro3, tmp3, 30, tmp4
    [B------:R-:W-:-:S01] @Pt3 IADD3.X tmp8, PT, PT, tmp8, RZ, Radd8, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro4, tmp4, 30, tmp5
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro5, tmp5, 30, tmp6
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro6, tmp6, 30, tmp7
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro7, tmp7, 30, tmp8
    [B------:R-:W-:-:S01] @Pt3 SHF.R.S32.HI Ro8, RZ, 30, tmp8
////end _mul_256_by_u31_add_shift
}

//---- _mul_P_by_32_add_shift  <- asm/mod_inv.asm -----------------------------------
FUNCTION _mul_P_by_32_add_shift(val=Rt0)
{ //Ro_cnt=9, Rt_cnt=1, Pt=[0,1],  Rval, RaddA
////start _mul_P_by_32_add_shift
    [B------:R-:W-:-:S05] @Pt3 IMAD.U32 val, Rval, 0xD2253531, RZ
    [B------:R-:W-:-:S05] @Pt3 LOP3.LUT val, val, 0x3fffffff, RZ, 0xc0, !PT
    [B------:R-:W-:-:S03] @Pt3 IMAD.WIDE.U32 Ro0, val, 0x000003D1, RZ
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro0, Pt0, PT, RaddA0, ~Ro0, RZ, !PT, PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro1, Pt0, Pt1, RaddA1, ~Ro1, ~val, Pt0, PT
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro2, Pt0, PT, RaddA2, 0xFFFFFFFE, RZ, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro0, Ro0, 30, Ro1
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro3, Pt0, PT, RaddA3, ~RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro1, Ro1, 30, Ro2
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro4, Pt0, PT, RaddA4, ~RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro2, Ro2, 30, Ro3
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro5, Pt0, PT, RaddA5, ~RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro3, Ro3, 30, Ro4
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro6, Pt0, PT, RaddA6, ~RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro4, Ro4, 30, Ro5
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro7, Pt0, PT, RaddA7, ~RZ, RZ, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro5, Ro5, 30, Ro6
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro8, PT, PT, val, ~RZ, RaddA8, Pt0, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro6, Ro6, 30, Ro7
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro7, Ro7, 30, Ro8
    [B------:R-:W-:-:S01] @Pt3 SHF.R.S32.HI Ro8, RZ, 30, Ro8
////end _mul_P_by_32_add_shift
}

//---- _mul_P_by_32_add3_shift  <- asm/mod_inv.asm ----------------------------------
FUNCTION _mul_P_by_32_add3_shift(val=Rt0)
{ //Ro_cnt=9, Rt_cnt=1, Pt=[0..2],  Rval
////start _mul_P_by_32_add3_shift
    [B------:R-:W-:-:S05] @Pt3 IMAD.U32 val, Rval, 0xD2253531, RZ
    [B------:R-:W-:-:S05] @Pt3 LOP3.LUT val, val, 0x3fffffff, RZ, 0xc0, !PT
    [B------:R-:W-:-:S05] @Pt3 IMAD.WIDE.U32 Ro0, val, 0x000003D1, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro0, Pt0, Pt1, RaddA0, ~Ro0, RaddB0, !PT, PT
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro1, Pt2, PT, Ro1, val, RZ, !PT, !PT
    [B------:R-:W-:-:S01] @Pt3 IADD3 val, val, -0x1, RZ
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro1, Pt0, Pt1, RaddA1, ~Ro1, RaddB1, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro2, PT, PT, RZ, RZ, RZ, Pt2, !PT
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro0, Ro0, 30, Ro1
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro2, Pt0, Pt1, RaddA2, ~Ro2, RaddB2, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro3, Pt0, Pt1, RaddA3, ~RZ, RaddB3, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro1, Ro1, 30, Ro2
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro4, Pt0, Pt1, RaddA4, ~RZ, RaddB4, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro2, Ro2, 30, Ro3
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro5, Pt0, Pt1, RaddA5, ~RZ, RaddB5, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro3, Ro3, 30, Ro4
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro6, Pt0, Pt1, RaddA6, ~RZ, RaddB6, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro4, Ro4, 30, Ro5
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro7, Pt0, Pt1, RaddA7, ~RZ, RaddB7, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro5, Ro5, 30, Ro6
    [B------:R-:W-:-:S01] @Pt3 IADD3.X Ro8, PT, PT, val, RaddA8, RaddB8, Pt0, Pt1
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro6, Ro6, 30, Ro7
    [B------:R-:W-:-:S01] @Pt3 SHF.R.U32 Ro7, Ro7, 30, Ro8
    [B------:R-:W-:-:S01] @Pt3 SHF.R.S32.HI Ro8, RZ, 30, Ro8
////end _mul_P_by_32_add3_shift
}

//---- _mul_P_by_32_add3_shift_nopredicate  <- asm/mod_inv.asm ----------------------
FUNCTION _mul_P_by_32_add3_shift_nopredicate(val=Rt0)
{ //Ro_cnt=9, Rt_cnt=1, Pt=[0..2],  Rval
////start _mul_P_by_32_add3_shift
    [B------:R-:W-:-:S05]    IMAD.U32 val, Rval, 0xD2253531, RZ
    [B------:R-:W-:-:S05]    LOP3.LUT val, val, 0x3fffffff, RZ, 0xc0, !PT
    [B------:R-:W-:-:S05]    IMAD.WIDE.U32 Ro0, val, 0x000003D1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro0, Pt0, Pt1, RaddA0, ~Ro0, RaddB0, !PT, PT
    [B------:R-:W-:-:S01]    IADD3.X Ro1, Pt2, PT, Ro1, val, RZ, !PT, !PT
    [B------:R-:W-:-:S01]    IADD3 val, val, -0x1, RZ
    [B------:R-:W-:-:S01]    IADD3.X Ro1, Pt0, Pt1, RaddA1, ~Ro1, RaddB1, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Ro2, PT, PT, RZ, RZ, RZ, Pt2, !PT
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro0, Ro0, 30, Ro1
    [B------:R-:W-:-:S04]    IADD3.X Ro2, Pt0, Pt1, RaddA2, ~Ro2, RaddB2, Pt0, Pt1
    [B------:R-:W-:-:S01]    IADD3.X Ro3, Pt0, Pt1, RaddA3, ~RZ, RaddB3, Pt0, Pt1
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro1, Ro1, 30, Ro2
    [B------:R-:W-:-:S01]    IADD3.X Ro4, Pt0, Pt1, RaddA4, ~RZ, RaddB4, Pt0, Pt1
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro2, Ro2, 30, Ro3
    [B------:R-:W-:-:S01]    IADD3.X Ro5, Pt0, Pt1, RaddA5, ~RZ, RaddB5, Pt0, Pt1
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro3, Ro3, 30, Ro4
    [B------:R-:W-:-:S01]    IADD3.X Ro6, Pt0, Pt1, RaddA6, ~RZ, RaddB6, Pt0, Pt1
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro4, Ro4, 30, Ro5
    [B------:R-:W-:-:S01]    IADD3.X Ro7, Pt0, Pt1, RaddA7, ~RZ, RaddB7, Pt0, Pt1
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro5, Ro5, 30, Ro6
    [B------:R-:W-:-:S01]    IADD3.X Ro8, PT, PT, val, RaddA8, RaddB8, Pt0, Pt1
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro6, Ro6, 30, Ro7
    [B------:R-:W-:-:S01]    SHF.R.U32 Ro7, Ro7, 30, Ro8
    [B------:R-:W-:-:S01]    SHF.R.S32.HI Ro8, RZ, 30, Ro8
////end _mul_P_by_32_add3_shift
}

//---- InvMod256  <- asm/mod_inv.asm ------------------------------------------------
FUNCTION InvMod256(val=Ri0, modp=Rt0, uu=Rt9, aa=Rt10, vv=Rt19, tmpA=Rt20, uv=Rt29, tmpB=Rt30, vu=Rt39, tmpC=Rt40, zeros=Rt20, _val=Rt49, _modp=Rt50, bc=Rt21, mulA=Rt22, mulB=Rt23, one=Rt51, two=URt0, tempA=Rt52, tempB=Rt53, tmpD=Rt54, tvars=Rt64)
{ //Ri_cnt=9(will be spoiled!), Ro_cnt=9, P=[0..3]
//Rt_cnt = 70,  URt=1
////start InvMod256
    [B------:R-:W-:-:S01]    MOV modp0, 0xFFFFFC2F
    [B------:R-:W-:-:S01]    IMAD modp1, RZ, RZ, 0xFFFFFFFE
    [B------:R-:W-:-:S01]    MOV modp2, 0xFFFFFFFF
    [B------:R-:W-:-:S01]    IMAD modp3, RZ, RZ, 0xFFFFFFFF
    [B------:R-:W-:-:S01]    MOV modp4, 0xFFFFFFFF
    [B------:R-:W-:-:S01]    IMAD modp5, RZ, RZ, 0xFFFFFFFF
    [B------:R-:W-:-:S01]    MOV modp6, 0xFFFFFFFF
    [B------:R-:W-:-:S01]    IMAD modp7, RZ, RZ, 0xFFFFFFFF
    [B------:R-:W-:-:S01]    MOV modp8, 0x00
    [B------:R-:W-:-:S01]    IMAD val8, RZ, RZ, RZ
    [B------:R-:W-:-:S01]    MOV one, 0x01
    [B------:R-:W-:-:S01]    UMOV two, 0x02
    [B------:R-:W-:-:S01]    MOV bc, 30
    [B------:R-:W-:-:S01]    MOV uu, 0x01
    [B------:R-:W-:-:S01]    IMAD vv, RZ, RZ, 0x01
    [B------:R-:W-:-:S01]    MOV uv, 0x00
    [B------:R-:W-:-:S01]    IMAD vu, RZ, RZ, 0x00
    [B------:R-:W-:-:S01]    MOV _val, val0
    [B------:R-:W-:-:S01]    IMAD _modp, RZ, RZ, modp0

inc_func _fast_find_first_bit(Ro=zeros, Rt=tvars, Rval=_val, Rone=one, Rbc=bc)

    [B------:R-:W-:-:S01]    ISETP.EQ.AND Pt3, PT, RZ, RZ, PT //set Pt3=PT

    [B------:R-:W-:-:S01]    IADD3 bc, bc, -zeros, RZ
    [B------:R-:W-:-:S01]    SHF.L.U32 uu, uu, zeros, RZ
    [B------:R-:W-:-:S03]    ISETP.GT.AND Pt0, PT, bc, RZ, PT
    [B------:R-:W-:-:S01]    SHF.L.U32 uv, uv, zeros, RZ
    [B------:R-:W-:-:S04]    SHF.R.S32.HI _val, RZ, zeros, _val
    [B------:R-:W-:-:S05]    LOP3.LUT tvars, _val, two, _modp, 0x48, !PT
.label_Start0:
    [B------:R-:W-:-:S02] @Pt0 IMAD mulA, tvars, one, -0x1
    [B------:R-:W-:-:S01] @Pt0 SHF.L.U32 tempA, one, bc, RZ
    [B------:R-:W-:-:S01]    BRA.CONV !Pt0, ~URZ `(.label_Done0)
    [B------:R-:W-:-:S01] @Pt0 IMAD _val, mulA, _modp, _val
    [B------:R-:W-:-:S04] @Pt0 IADD3 mulB, -mulA, RZ, RZ
    [B------:R-:W-:-:S01] @Pt0 LOP3.LUT tempA, tempA, _val, RZ, 0xfc, !PT
    [B------:R-:W-:-:S01] @Pt0 IMAD _modp, mulB, _val, _modp
    [B------:R-:W-:-:S01] @Pt0 IMAD vu, mulA, uu, vu
    [B------:R-:W-:-:S03] @Pt0 IADD3 tempB, -tempA, RZ, RZ
    [B------:R-:W-:-:S01] @Pt0 IMAD vv, mulA, uv, vv
    [B------:R-:W-:-:S03] @Pt0 LOP3.LUT tempA, tempA, tempB, RZ, 0xc0, !PT //(z & -z)
    [B------:R-:W-:-:S01] @Pt0 IMAD uu, mulB, vu, uu
    [B------:R-:W-:-:S03] @Pt0 I2FP.F32.S32 tempA, tempA
    [B------:R-:W-:-:S01] @Pt0 IMAD uv, mulB, vv, uv
    [B------:R-:W-:-:S04] @Pt0 LEA.HI zeros, tempA, 0xffffff81, RZ, 9 //(int >> 23) - 127
    [B------:R-:W-:-:S01] @Pt0 IADD3 bc, bc, -zeros, RZ
    [B------:R-:W-:-:S01] @Pt0 SHF.L.U32 uu, uu, zeros, RZ
    [B------:R-:W-:-:S01] @Pt0 SHF.L.U32 uv, uv, zeros, RZ
    [B------:R-:W-:-:S01] @Pt0 SHF.R.S32.HI _val, RZ, zeros, _val
    [B------:R-:W-:-:S01]    ISETP.GT.AND Pt0, PT, bc, RZ, Pt0
    [B------:R-:W-:-:S01] @Pt0 LOP3.LUT tvars, _val, two, _modp, 0x48, !PT // Rt = (Rv ^ Rm) & 0x2
    [B------:R-:W-:Y:S01]    BRA `(.label_Start0)
.label_Done0:

    //set uu and vv positive
    [B------:R-:W-:Y:S04]    ISETP.LT.AND Pt0, PT, uu, RZ, PT
    [B------:R-:W-:Y:S09]    ISETP.LT.AND Pt1, PT, vv, RZ, PT
    [B------:R-:W-:-:S01] @Pt0 IADD3 uv, RZ, RZ, -uv
    [B------:R-:W-:-:S01] @Pt0 IADD3 uu, RZ, RZ, -uu
    [B------:R-:W-:-:S01] @Pt1 IADD3 vv, RZ, RZ, -vv
    [B------:R-:W-:-:S01] @Pt1 IMAD vu, RZ, RZ, -vu

inc_func _mul_256_by_i32(Ro=tmpB, Pt=0, Rval=val, Ri=uv, Rt=tvars)
inc_func _mul_256_by_i32(Ro=tmpC, Pt=0, Rval=modp, Ri=vu, Rt=tvars)
inc_func _mul_256_by_u31_add_shift(Ro=val, Pt=0, Rval=val, Ri=vv, Radd=tmpC, Rt=tmpD)
inc_func _mul_256_by_u31_add_shift(Ro=modp, Pt=0, Rval=modp, Ri=uu, Radd=tmpB, Rt=tmpD)

//set_288_i32
    [B------:R-:W-:-:S04]    SHF.R.S32.HI tmpB1, RZ, 0x1f, uv  // res = (val < 0) ? 0xFFFFFFFF : 0
    [B------:R-:W-:-:S01]    MOV tmpB0, uv
    [B------:R-:W-:-:S01]    MOV tmpB2, tmpB1
    [B------:R-:W-:-:S01]    IMAD tmpB3, RZ, RZ, tmpB1
    [B------:R-:W-:-:S01]    MOV tmpB4, tmpB1
    [B------:R-:W-:-:S01]    IMAD tmpB5, RZ, RZ, tmpB1
    [B------:R-:W-:-:S01]    MOV tmpB6, tmpB1
    [B------:R-:W-:-:S01]    IMAD tmpB7, RZ, RZ, tmpB1
    [B------:R-:W-:-:S01]    MOV tmpB8, tmpB1
//set_288_i32, vv always positive
    [B------:R-:W-:-:S01]    IMAD tmpD0, RZ, RZ, vv
    [B------:R-:W-:-:S01]    MOV tmpD1, 0x00
    [B------:R-:W-:-:S01]    IMAD tmpD2, RZ, RZ, 0x00
    [B------:R-:W-:-:S01]    MOV tmpD3, 0x00
    [B------:R-:W-:-:S01]    IMAD tmpD4, RZ, RZ, 0x00
    [B------:R-:W-:-:S01]    MOV tmpD5, 0x00
    [B------:R-:W-:-:S01]    IMAD tmpD6, RZ, RZ, 0x00
    [B------:R-:W-:-:S01]    MOV tmpD7, 0x00
    [B------:R-:W-:-:S01]    MOV tmpD8, 0x00

inc_func _mul_P_by_32_add_shift(Ro=Ro0, Pt=0, Rval=tmpB, RaddA=tmpB, Rt=tvars)
inc_func _mul_P_by_32_add_shift(Ro=aa, Pt=0, Rval=tmpD, , RaddA=tmpD, Rt=tvars)

//START OF MAIN LOOP
.label_Start2:
    [B------:R-:W-:-:S02] @Pt3 MOV tvars0, 0x40000000
    [B------:R-:W-:-:S01] @Pt3 IMAD bc, RZ, RZ, 30
    [B------:R-:W-:-:S01] @Pt3 IMAD _modp, modp0, 0x01, RZ
    [B------:R-:W-:-:S03] @Pt3 LOP3.LUT tvars0, tvars0, val0, RZ, 0xfc, !PT //(val | R7)   R2=val
    [B------:R-:W-:-:S01] @Pt3 IMAD vu, RZ, RZ, RZ
    [B------:R-:W-:-:S03] @Pt3 IADD3 tvars1, -tvars0, RZ, RZ //z=Rt0
    [B------:R-:W-:-:S01] @Pt3 IMAD uv, RZ, RZ, RZ
    [B------:R-:W-:-:S02] @Pt3 LOP3.LUT tvars0, tvars0, tvars1, RZ, 0xc0, !PT //(z & -z)
    [B------:R-:W-:-:S04] @Pt3 MOV uu, 0x01
    [B------:R-:W-:-:S02] @Pt3 I2FP.F32.S32 tvars0, tvars0 //float to int
    [B------:R-:W-:-:S04] @Pt3 MOV vv, 0x01
    [B------:R-:W-:-:S02] @Pt3 LEA.HI zeros, tvars0, 0xffffff81, RZ, 9 //(int >> 23) - 127
    [B------:R-:W-:-:S04] @Pt3 MOV _val, val0
    [B------:R-:W-:-:S01] @Pt3 IADD3 bc, bc, -zeros, RZ
    [B------:R-:W-:-:S01] @Pt3 SHF.R.S32.HI _val, RZ, zeros, _val
    [B------:R-:W-:-:S01]    ISETP.GT.AND Pt0, PT, bc, RZ, Pt3
    [B------:R-:W-:-:S03] @Pt3 SHF.L.U32 uu, uu, zeros, RZ
    [B------:R-:W-:-:S04] @Pt3 LOP3.LUT tvars, _val, two, _modp, 0x48, !PT
    [B------:R-:W-:-:S05] @Pt3 SHF.L.U32 uv, uv, zeros, RZ
.label_Start1: //tight loop
    [B------:R-:W-:-:S02] @Pt0 IMAD mulA, tvars, one, -0x1
    [B------:R-:W-:-:S01] @Pt0 SHF.L.U32 tempA, one, bc, RZ
    [B------:R-:W-:-:S01]    BRA.CONV !Pt0, ~URZ `(.label_Done1)
    [B------:R-:W-:-:S01] @Pt0 IMAD _val, mulA, _modp, _val
    [B------:R-:W-:-:S04] @Pt0 IADD3 mulB, -mulA, RZ, RZ
    [B------:R-:W-:-:S01] @Pt0 LOP3.LUT tempA, tempA, _val, RZ, 0xfc, !PT
    [B------:R-:W-:-:S01] @Pt0 IMAD _modp, mulB, _val, _modp
    [B------:R-:W-:-:S01] @Pt0 IMAD vu, mulA, uu, vu
    [B------:R-:W-:-:S03] @Pt0 IADD3 tempB, -tempA, RZ, RZ
    [B------:R-:W-:-:S01] @Pt0 IMAD vv, mulA, uv, vv
    [B------:R-:W-:-:S03] @Pt0 LOP3.LUT tempA, tempA, tempB, RZ, 0xc0, !PT //(z & -z)
    [B------:R-:W-:-:S01] @Pt0 IMAD uu, mulB, vu, uu
    [B------:R-:W-:-:S03] @Pt0 I2FP.F32.S32 tempA, tempA
    [B------:R-:W-:-:S01] @Pt0 IMAD uv, mulB, vv, uv
    [B------:R-:W-:-:S04] @Pt0 LEA.HI zeros, tempA, 0xffffff81, RZ, 9 //(int >> 23) - 127
    [B------:R-:W-:-:S01] @Pt0 IADD3 bc, bc, -zeros, RZ
    [B------:R-:W-:-:S01] @Pt0 SHF.L.U32 uu, uu, zeros, RZ
    [B------:R-:W-:-:S01] @Pt0 SHF.L.U32 uv, uv, zeros, RZ
    [B------:R-:W-:-:S01] @Pt0 SHF.R.S32.HI _val, RZ, zeros, _val
    [B------:R-:W-:-:S01]    ISETP.GT.AND Pt0, PT, bc, RZ, Pt0
    [B------:R-:W-:-:S01] @Pt0 LOP3.LUT tvars, _val, two, _modp, 0x48, !PT // Rt = (Rv ^ Rm) & 0x2
    [B------:R-:W-:Y:S01]    BRA `(.label_Start1)
.label_Done1:

    //set uu and vv positive
    [B------:R-:W-:Y:S04]    ISETP.LT.AND Pt0, PT, uu, RZ, Pt3
    [B------:R-:W-:Y:S09]    ISETP.LT.AND Pt1, PT, vv, RZ, Pt3
    [B------:R-:W-:-:S01] @Pt0 IADD3 uu, -uu, RZ, RZ
    [B------:R-:W-:-:S01] @Pt0 IADD3 uv, -uv, RZ, RZ
    [B------:R-:W-:-:S01] @Pt1 IADD3 vv, -vv, RZ, RZ
    [B------:R-:W-:-:S01] @Pt1 IADD3 vu, -vu, RZ, RZ

inc_func _mul_256_by_i32(Ro=tmpB, Pt=0, Rval=val, Ri=uv, Rt=tvars)
inc_func _mul_256_by_i32(Ro=tmpC, Pt=0, Rval=modp, Ri=vu, Rt=tvars)
inc_func _mul_256_by_u31_add_shift(Ro=val, Pt=0, Rval=val, Ri=vv, Radd=tmpC, Rt=tmpD)
    [B------:R-:W-:-:S01] @Pt3 LOP3.LUT tempA, val0, val1, val2,  0xFE, !PT
    [B------:R-:W-:-:S01] @Pt3 LOP3.LUT tempB, val3, val4, val5,  0xFE, !PT
    [B------:R-:W-:-:S01] @Pt3 LOP3.LUT zeros, val6, val7, val8,  0xFE, !PT
inc_func _mul_256_by_u31_add_shift(Ro=modp, Pt=0, Rval=modp, Ri=uu, Radd=tmpB, Rt=tmpD)
    [B------:R-:W-:-:S01] @Pt3 LOP3.LUT tempA, tempA, tempB, zeros, 0xFE, !PT
inc_func _mul_256_by_i32(Ro=tmpB, Pt=0, Rval=aa, Ri=uv, Rt=tvars)
    [B------:R-:W-:-:S01]    ISETP.NE.AND Pt1, PT, tempA, RZ, Pt3
inc_func _mul_256_by_u31(Ro=tmpA, Pt=0, Rval=Ro0, Ri=uu, Rt=tvars)

//IF (val[0..8] == 0) THEN STOP MAIN LOOP
    [B------:R-:W-:-:S01]    BRA.CONV !Pt1, ~URZ `(.label_Done2)
    [B------:R-:W-:-:S01]    ISETP.EQ.AND Pt3, PT, RZ, RZ, Pt1 //set Pt3=Pt1

inc_func _mul_256_by_i32(Ro=tmpC, Pt=0, Rval=Ro0, Ri=vu, Rt=tvars)
    [B------:R-:W-:-:S01] @Pt3 IADD3 tempA, tmpA0, tmpB0, RZ
inc_func _mul_256_by_u31(Ro=tmpD, Pt=0, Rval=aa, Ri=vv, Rt=tvars)
    [B------:R-:W-:-:S01] @Pt3 IADD3 tempB, tmpC0, tmpD0, RZ

inc_func _mul_P_by_32_add3_shift(Ro=Ro0, Pt=0, Rval=tempA, RaddA=tmpA, RaddB=tmpB, Rt=tvars)
inc_func _mul_P_by_32_add3_shift(Ro=aa, Pt=0, Rval=tempB, RaddA=tmpC, RaddB=tmpD, Rt=tvars)
//END OF MAIN WHILE
    [B------:R-:W-:Y:S01]    BRA `(.label_Start2)
.label_Done2:

    [B------:R-:W-:Y:S04]    IADD3 tempA, tmpA0, tmpB0, RZ
    [B------:R-:W-:-:S01]    ISETP.LT.AND Pt3, PT, modp8, RZ, PT

inc_func _mul_P_by_32_add3_shift_nopredicate(Ro=Ro0, Pt=0, Rval=tempA, RaddA=tmpA, RaddB=tmpB, Rt=tvars)

//if ((int)modp[8] < 0) neg_288(res)
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro0, Pt0, PT, RZ, ~Ro0, RZ, PT, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro1, Pt0, PT, RZ, ~Ro1, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro2, Pt0, PT, RZ, ~Ro2, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro3, Pt0, PT, RZ, ~Ro3, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro4, Pt0, PT, RZ, ~Ro4, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro5, Pt0, PT, RZ, ~Ro5, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro6, Pt0, PT, RZ, ~Ro6, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt3 IADD3.X Ro7, Pt0, PT, RZ, ~Ro7, RZ, Pt0, !PT
    [B------:R-:W-:-:S05] @Pt3 IADD3.X Ro8, PT, PT, RZ, ~Ro8, RZ, Pt0, !PT

//	while ((int)res[8] < 0) add_288_P(res);
.label_Start3:
    [B------:R-:W-:Y:S13]    ISETP.LT.AND Pt1, PT, Ro8, RZ, PT
    [B------:R-:W-:-:S01]    BRA.CONV !Pt1, ~URZ `(.label_Done3)
    [B------:R-:W-:-:S04] @Pt1 IADD3 Ro0, Pt0, Ro0, 0xFFFFFC2F, RZ
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro1, Pt0, PT, Ro1, 0xFFFFFFFE, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro2, Pt0, PT, Ro2, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro3, Pt0, PT, Ro3, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro4, Pt0, PT, Ro4, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro5, Pt0, PT, Ro5, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro6, Pt0, PT, Ro6, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro7, Pt0, PT, Ro7, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro8, Pt0, PT, Ro8, RZ, RZ, Pt0, !PT
    [B------:R-:W-:Y:S01]    BRA `(.label_Start3)
.label_Done3:

// while ((int)res[8] > 0) sub_288_P(res);
.label_Start4:
    [B------:R-:W-:Y:S13]    ISETP.GT.AND Pt1, PT, Ro8, RZ, PT
    [B------:R-:W-:-:S01]    BRA.CONV !Pt1, ~URZ `(.label_Done4)
    [B------:R-:W-:-:S04] @Pt1 IADD3   Ro0, Pt0, Ro0, 0x000003D1, RZ
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro1, Pt0, PT, Ro1, 0x00000001, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro2, Pt0, PT, Ro2, 0x00000000, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro3, Pt0, PT, Ro3, 0x00000000, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro4, Pt0, PT, Ro4, 0x00000000, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro5, Pt0, PT, Ro5, 0x00000000, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro6, Pt0, PT, Ro6, 0x00000000, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro7, Pt0, PT, Ro7, 0x00000000, RZ, Pt0, !PT
    [B------:R-:W-:-:S04] @Pt1 IADD3.X Ro8, PT, PT, Ro8, 0xFFFFFFFF, RZ, Pt0, !PT
    [B------:R-:W-:Y:S01]    BRA `(.label_Start4)
.label_Done4:
////end InvMod256
}
