#!/usr/bin/env python3
"""Regenerate asm/tk/inc.asm from Kernel02's asm/mod_*.asm, then prove the copy is faithful.

    python3 mkinc.py

Extracts whole FUNCTION blocks byte-for-byte and diffs every emitted body back against its
origin line for line. It never retypes an instruction, which is the point: these are
hand-scheduled control codes, one wrong character is a wrong answer on hardware rather than
a build failure, and README.md records three separate defects of exactly that shape.

Run this only to re-sync inc.asm with the vendored sources. Once a body here is DELIBERATELY
changed -- C8's missing conditional subtract in MulMod256/SqrMod256 is the one on the list --
inc.asm becomes the source of truth, this script will report the difference as a mismatch,
and that report is correct rather than a failure to be silenced. Move the name out of WANT
and say so in inc.asm's header when that happens.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASM = os.path.abspath(os.path.join(HERE, ".."))
OUT = os.path.join(HERE, "inc.asm")

# (source file, function name), in the order they appear in inc.asm. This IS the list of
# what the kernel may call: anything main.asm adds an inc_func/call_func for must be added
# here too, or the build fails at "failed to calc FUNCTION".
WANT = [
    ("mod_sub.asm", "Copy256"),
    ("mod_sub.asm", "SubMod256"),
    ("mod_sub.asm", "SubMod256_3"),
    ("mod_sub.asm", "NegMod256"),
    ("mod_mul.asm", "MulMod256"),
    ("mod_mul.asm", "SqrMod256"),
    ("mod_inv.asm", "_fast_find_first_bit"),
    ("mod_inv.asm", "_mul_256_by_i32"),
    ("mod_inv.asm", "_mul_256_by_u31"),
    ("mod_inv.asm", "_mul_256_by_u31_add_shift"),
    ("mod_inv.asm", "_mul_P_by_32_add_shift"),
    ("mod_inv.asm", "_mul_P_by_32_add3_shift"),
    ("mod_inv.asm", "_mul_P_by_32_add3_shift_nopredicate"),
    ("mod_inv.asm", "InvMod256"),
]

FUNC = re.compile(r"^FUNCTION\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")


def parse(path):
    """name -> exact source text of the whole FUNCTION block, line endings preserved."""
    with open(path, "r", encoding="utf-8", newline="") as f:
        lines = f.read().splitlines(keepends=True)
    out, i = {}, 0
    while i < len(lines):
        m = FUNC.match(lines[i])
        if not m:
            i += 1
            continue
        name, start, depth, seen = m.group(1), i, 0, False
        while i < len(lines):
            s = lines[i].lstrip()
            if s.startswith("{"):
                depth += 1
                seen = True
            elif s.startswith("}"):
                depth -= 1
            i += 1
            if seen and depth == 0:
                break
        assert seen and depth == 0, f"unbalanced block for {name} in {path}"
        out[name] = "".join(lines[start:i])
    return out


def lines_of(block):
    """Content lines with the terminator normalised away. Exact for every instruction, and
    tolerant of the one real difference: mod_inv.asm ends at InvMod256's closing brace with
    NO trailing newline, so the origin's last line has no terminator and the copy's does."""
    return [l.rstrip("\r\n") for l in block.splitlines()]


src = {f: parse(os.path.join(ASM, f)) for f in {f for f, _ in WANT}}
for f, n in WANT:
    if n not in src[f]:
        sys.exit(f"FUNCTION {n} not found in {f}")

HEADER = """\
// asm/tk/inc.asm -- the field-arithmetic units this kernel actually uses.
//
// GENERATED BY asm/tk/mkinc.py -- DO NOT HAND-EDIT WITHOUT READING THAT FILE FIRST.
// Every instruction line below is copied byte-for-byte out of Kernel02's asm/mod_mul.asm,
// asm/mod_sub.asm and asm/mod_inv.asm, and the generator diffs each body back against its
// origin line for line before writing. It is generated rather than transcribed on purpose:
// these are hand-scheduled control codes, one wrong character is a wrong answer on hardware
// and not a build failure, and asm/tk/README.md records three defects of exactly that shape.
//
// WHY THIS FILE EXISTS. build.sh used to copy mod_mul.asm, mod_sub.asm and mod_inv.asm into
// the project directory at build time, because RCAsm concatenates every .asm it finds there
// and asm/ also holds Kernel02's own main.asm/fuse.asm/newKernelB.asm, which declare their
// own KERNELs. That kept one copy of the sources but made the build depend on a tree this
// kernel does not otherwise use, and pulled in four routines it never calls.
//
// WHAT IS HERE AND WHAT IS NOT. Exactly the transitive closure of what main.asm calls:
//
//     Copy256                      every 256-bit copy in main.asm goes through this
//     SubMod256  SubMod256_3  NegMod256
//     MulMod256  SqrMod256
//     InvMod256  + its seven _-prefixed helpers, all of which it uses
//
// Deliberately absent, because nothing reaches them: MadMod256 and SqrAddMod256 (mod_mul),
// AddMod256 and Zero256 (mod_sub). Dropping them changes no emitted byte -- RCAsm only ever
// emits a body some inc_func/call_func names -- so this is a smaller file to audit and
// nothing else. Anything main.asm adds a call to must be added to mkinc.py's WANT list too.
//
// Copy256's tail is S05, and that is load-bearing rather than incidental: it is the longest
// tail of the eight hand-written copy blocks it replaced, so every substitution LENGTHENED a
// stall or left it alone. Shortening one is what reads a stale register. See README.md.
//
// THE PRECONDITIONS TRAVEL WITH THE CODE, and two of them are not in the headers below:
//
//   * InvMod256 REQUIRES ALL ACTIVE THREADS IN THE WARP (its own comment, kept below). The
//     batch loop's uniform trip count is what supplies that; see main.asm's note on rem.
//   * InvMod256's Ro is NINE registers and its Rt is SEVENTY-THREE -- neither is the number
//     its own header advertises (Rt_cnt = 70). Both were found by measuring the emitted
//     cubin. Getting Ro wrong lands its overflow word on Rt0 and corrupts every inversion,
//     in a build that assembles and passes every offline checker. See main.asm's register
//     table, which is where the allocation those numbers constrain actually lives.
//
// C8 APPLIES TO MulMod256 AND SqrMod256 AS WRITTEN. They return a*b mod P in [0, 2^256)
// rather than [0, P) -- no final conditional subtract -- exactly as GpuCore.cu's mul_mod
// does. Measured on hardware: (P-1)^2 and 2*(P+1)/2 both come back as P+1. That is fine for
// the points-only kernel, which consumes no parity, and it is NOT fine once the hash layer
// returns, because the compressed-pubkey prefix is derived from bit 0 and P is odd. Fixing
// it is a change to THIS file, and the first one that will make mkinc.py report a mismatch.
"""

parts = [HEADER]
for f, n in WANT:
    parts.append(f"\n//---- {n}  <- asm/{f} " + "-" * max(0, 68 - len(n) - len(f)) + "\n")
    body = src[f][n]
    parts.append(body if body.endswith("\n") else body + "\n")

# CRLF throughout, which is what main.asm and all three vendored sources use.
text = "".join(parts).replace("\r\n", "\n").replace("\n", "\r\n")
with open(OUT, "w", encoding="utf-8", newline="") as f:
    f.write(text)

back = parse(OUT)
bad = 0
for f, n in WANT:
    a, b = lines_of(src[f][n]), lines_of(back.get(n, ""))
    if a != b:
        print(f"  MISMATCH {n}: {len(a)} origin lines vs {len(b)} emitted")
        for k, (x, y) in enumerate(zip(a, b)):
            if x != y:
                print(f"    first at body line {k+1}:\n      origin  {x!r}\n      emitted {y!r}")
                break
        bad += 1
extra = set(back) - {n for _, n in WANT}
if extra:
    print(f"  UNEXPECTED functions in output: {sorted(extra)}")
    bad += 1
nbody = sum(len(lines_of(src[f][n])) for f, n in WANT)
print(f"wrote {OUT}")
print(f"  {len(back)} FUNCTIONs, {len(text.splitlines())} lines total, {nbody} of them body lines")
print("  line-for-line against origin: " + (f"OK, all {len(WANT)}" if not bad else "FAILED"))
sys.exit(1 if bad else 0)
