#!/usr/bin/env python3
# Turn the lifted hash bodies (raw registers) into PROPERLY PARAMETRIZED RCAsm FUNCTIONs whose
# signatures declare real input/output slot classes (Ri/Rio/Rt/URt), matching the getPublish style.
# The transform is a pure register-name remap -- every PHYSICAL register number is preserved -- so
# the assembled SASS is byte-identical to a fixed renumber; verify by SASS diff.
#
# Both getHash160_w2 (word-2 only) and getHash160_33 (full 5-word) share ONE input ABI, so ONE map:
#   R6..R13  -> Ri0..Ri7   the 8 little-endian SHA input words (= the walk's PntX0..PntX7)
#   R4       -> Rio0        prefix byte IN; also an output word (in/out -> Rio)
#   UR4      -> URt0        a PRMT-select uniform temp, set inside the body
#   every other R<n> -> Rt<n>   bulk temps (the body uses raw Rt slots)
#
# The caller binds all four bases so the ABI is self-documenting, e.g.
#   call_func getHash160_33(Ri=R54, Rio=R52, Rt=MulB, URt=uHashSel, Ret="...BRXU.U uCallH,0x00")
# With Rt=R48 that lands Rt0..Rt59 on R48..R107, Ri0..Ri7 on R54..R61, Rio0 on R52 -- the registers
# the verified bodies used, hence byte-identical. Regenerate; do NOT hand-edit the outputs.
import re

r_re  = re.compile(r'(?<![A-Za-z0-9_])R(\d+)\b')
ur_re = re.compile(r'\bUR4\b')

def mapreg(n):
    if n == 4:        return 'Rio0'           # prefix in / word0 out (shared register -> in/out class)
    if 6 <= n <= 13:  return 'Ri%d' % (n - 6) # the 8 SHA input words
    return 'Rt%d' % n                          # bulk temps

def xform(line):
    line = r_re.sub(lambda m: mapreg(int(m.group(1))), line)
    line = ur_re.sub('URt0', line)
    return line

def parametrize(src, dst, header, tag):
    lines = open(src).read().splitlines()
    body, depth, seen_open = [], 0, False
    for ln in lines:
        s = ln.strip()
        if s == '{':
            depth += 1; seen_open = True; continue
        if s == '}':
            depth -= 1; continue
        if seen_open and depth >= 1:
            body.append(xform(ln))
    body_joined = "".join(b + "\n" for b in body)
    assert not r_re.search(body_joined), "unmapped R<n> remains in " + src
    assert not ur_re.search(body_joined), "unmapped UR4 remains in " + src
    with open(dst, "w", newline="\n") as f:
        f.write(header + "{\n" + body_joined + "}\n")
    def rng(cls):
        ns = [int(m.group(1)) for m in re.finditer(r'\b%s(\d+)\b' % cls, body_joined)]
        return "%s0..%s%d" % (cls, cls, max(ns)) if ns else "-"
    n = sum(1 for b in body if b.lstrip().startswith('['))
    print("wrote %-24s instrs=%-4d Ri=%-9s Rio=%-5s Rt=%-9s URt=%s"
          % (dst.split('/')[-1], n, rng('Ri'), rng('Rio'), rng('Rt'), rng('URt')))

W2_HEADER = """\
// Lifted getHash160_w2 (SHA-256 + trimmed RIPEMD-160 word-2), extracted from a fresh compile of
// GpuCore.cu's getHash160_w2_from_limbs. 2009 instrs, 32-bit only, no barriers/align. GENERATED by
// parametrize_hash.py from hd_hash_inc.asm -- do NOT hand-edit; regenerate.
//
// PARAMETRIZED (RCAsm slot classes; the caller binds each base at the call site):
//   input   x    = Ri0..Ri7   the 8 little-endian words of X (the walk marshals PntX0..PntX7);
//                             Ri0=lo32(x.v[0]) .. Ri7=hi32(x.v[3])
//   in/out  pfx  = Rio0        prefix byte IN (0x02|(y&1)); RIPEMD-160 word 2 OUT -- SAME register
//   temps   tmp  = Rt0..Rt58   scratch (raw Rt slots throughout the body)
//   uniform sel  = URt0        a PRMT-select uniform temp (set inside the body; bind to a FREE uniform)
// Bind Rt to the base of a 59-register dead span (walk uses Rt=MulB=R48 -> R48..R106), Ri=R54, Rio=R52
// -- reproduces the verified body's registers byte-for-byte. RET.ABS.NODEC dropped on lift; call_func
// appends the BRXU return. Body bit-exact vs hashgolden.bin.
FUNCTION getHash160_w2(x=Ri0, pfx=Rio0, tmp=Rt0, sel=URt0)
"""

H33_HEADER = """\
// Lifted getHash160_33 (SHA-256 + FULL RIPEMD-160, all 5 words), extracted from a fresh compile of
// GpuCore.cu's getHash160_33_from_limbs -- the __noinline__ sibling of getHash160_w2, called by
// hash160_full_match on the cold path (~2^-32). 2044 instrs, 32-bit only, no barriers/align/mem.
// GENERATED by parametrize_hash.py from hd_hash33_inc.asm -- do NOT hand-edit; regenerate.
//
// PARAMETRIZED (same input ABI as getHash160_w2; the caller binds each base at the call site):
//   input   x    = Ri0..Ri7   the 8 little-endian words of X (Ri0=lo32(x.v[0]) .. Ri7=hi32(x.v[3]))
//   in/out  pfx  = Rio0        prefix byte IN; also hash160 word 0 OUT (shared register)
//   temps   tmp  = Rt0..Rt59   scratch (raw Rt slots)
//   uniform sel  = URt0        a PRMT-select uniform temp (bind to a FREE uniform)
// OUTPUTS (hash160 words 0..4, little-endian) land in, with the standard Rt=R48/Ri=R54/Rio=R52 bind:
//   word0 = Rio0 (R52)   word1 = Rt5 (R53)   word2 = Ri0 (R54)   word3 = Ri1 (R55)   word4 = Ri2 (R56)
//   -- CONTIGUOUS R52..R56, so the caller reads 5 consecutive registers for hash160_full_match; word2
//   is the filter word (== getHash160_w2's output value). RET.ABS.NODEC dropped; call_func appends BRXU.
FUNCTION getHash160_33(x=Ri0, pfx=Rio0, tmp=Rt0, sel=URt0)
"""

if __name__ == "__main__":
    parametrize("hd_hash_inc.asm",   "hd_hash_inc_param.asm",   W2_HEADER,  "w2")
    parametrize("hd_hash33_inc.asm", "hd_hash33_inc_param.asm", H33_HEADER, "h33")
