#!/usr/bin/env python3
"""Test vectors for MulMod256 over the secp256k1 prime.

Deliberately NOT generated from this project's host MulModP: DEVPLAN C10 records that
EcInt.cpp's MulModP leaves results in [P, 2^256) rather than [0, P), so using it as the
oracle would either mask a real defect or invent a fake one. Python's arbitrary-precision
(a*b) % P has no such ambiguity.

Emits a C header of 4x u64 little-endian limb triples (a, b, expected).
"""
import random, sys

P = (1 << 256) - (1 << 32) - 977
assert P == 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F

def limbs(x):
    return [(x >> (64 * i)) & 0xFFFFFFFFFFFFFFFF for i in range(4)]

def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 256
    rnd = random.Random(20260813)          # fixed seed: the fixture must be reproducible

    cases = []

    # Edge cases first -- these are where an "almost reduced" implementation shows itself.
    K = (1 << 32) + 977                     # P = 2^256 - K
    edge = [
        (0, 0), (1, 1), (0, 1), (1, 0),
        (P - 1, 1), (1, P - 1), (P - 1, P - 1),
        (P - 1, 2), (2, P - 1),
        # 2 * (P+1)/2 == P+1: the exact witness DEVPLAN C8 uses against our own mul_mod.
        (2, (P + 1) // 2), ((P + 1) // 2, 2),
        (1 << 255, 2), (2, 1 << 255),
        ((1 << 256) - 1 - K, 1),            # largest value < P
        (K, K), (P - K, P - K),
        (0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF),
        (1 << 128, 1 << 128),               # product straddles the limb boundary
    ]
    for a, b in edge:
        cases.append((a % P, b % P))

    while len(cases) < n:
        cases.append((rnd.randrange(P), rnd.randrange(P)))

    out = []
    out.append("// Generated by gen_vectors.py -- do not edit.")
    out.append("// secp256k1 P = 2^256 - 2^32 - 977; expected = (a * b) mod P, fully reduced.")
    out.append("// Layout: 4x u64 little-endian limbs, a then b then expected.")
    out.append("#define MULMOD_CASES %d" % len(cases))
    out.append("static const unsigned long long kMulModVectors[MULMOD_CASES][3][4] = {")
    for a, b in cases:
        e = (a * b) % P
        f = lambda x: "{" + ",".join("0x%016XULL" % v for v in limbs(x)) + "}"
        out.append("  {%s,%s,%s}," % (f(a), f(b), f(e)))
    out.append("};")

    txt = "\n".join(out) + "\n"
    open("mulmod_vectors.h", "w").write(txt)
    print("wrote mulmod_vectors.h: %d cases (%d edge, %d random)"
          % (len(cases), len(edge), len(cases) - len(edge)))

    # Sanity: the identity every implementation must satisfy, checked independently.
    bad = 0
    for a, b in cases:
        e = (a * b) % P
        if e >= P or (a * b - e) % P != 0:
            bad += 1
    print("self-check: %d/%d vectors consistent, all reduced to [0,P)" % (len(cases) - bad, len(cases)))

if __name__ == "__main__":
    main()
